// Code generated by sqlc. DO NOT EDIT.
// source: logs.sql

package db

import (
	"context"
	"database/sql"
)

const insertLog = `-- name: InsertLog :one
INSERT INTO logs (
  inserts,
  updates,
  errors,
  timestamp_started,
  timestamp_finished

) VALUES (
  $1, $2, $3, $4, $5
) 
RETURNING id, inserts, updates, errors, timestamp_started, timestamp_finished
`

type InsertLogParams struct {
	Inserts           sql.NullInt32 `json:"inserts"`
	Updates           sql.NullInt32 `json:"updates"`
	Errors            sql.NullInt32 `json:"errors"`
	TimestampStarted  sql.NullTime  `json:"timestamp_started"`
	TimestampFinished sql.NullTime  `json:"timestamp_finished"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, insertLog,
		arg.Inserts,
		arg.Updates,
		arg.Errors,
		arg.TimestampStarted,
		arg.TimestampFinished,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Inserts,
		&i.Updates,
		&i.Errors,
		&i.TimestampStarted,
		&i.TimestampFinished,
	)
	return i, err
}
